#!/bin/bash
date=$(date +"%Y-%m-%d")
rep=$HOME/Images/bing

if test -f $rep/bing-$date; then exit 1; fi

data=$(wget -qO- "https://www.bing.com/HPImageArchive.aspx?idx=0&n=1")
baseurl=$(grep -oPm1 "(?<=<urlBase>)[^<]+" <<< $data)

wget -O $rep/bing-$date https://bing.com$baseurl\_UHD.jpg
cp $rep/bing-$date ~/.config/i3/wallpaper.jpg
feh --bg-fill ~/.config/i3/wallpaper.jpg