#!/bin/bash
pid=$(</tmp/ffmpeg.pid)

if ps -p $pid > /dev/null; then
    kill $pid
    rm /tmp/ffmpeg.pid
    exit 1
fi

slop=$(slop -f "%x %y %w %h %g %i") || exit 1
read -r X Y W H G ID < <(echo $slop)

date=$(date +"%Y-%m-%d-%H-%M-%S")
ffmpeg -f pulse -i alsa_output.pci-0000_00_1f.3.analog-stereo.monitor -f x11grab -s "$W"x"$H" -i :0.0+$X,$Y -acodec aac -vcodec libx264 -crf 23 -preset ultrafast ~/Vidéos/Captures/rc-$date.mp4 &
echo "$!" > /tmp/ffmpeg.pid
echo "file://$HOME/Vidéos/Captures/rc-$date.mp4" | xclip -sel clip -t text/uri-list -i